services:
  app:
    image: ghcr.io/davchs/github-workflow-example/app:0.2
    build:
      context: .docker/php
      target: app
    container_name: symfony_app
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    ports:
      - "8383:8383"
    depends_on:
      - database
    networks:
      - symfony_network

  cli:
    image: ghcr.io/davchs/github-workflow-example/cli:0.2
    build:
      context: .docker/php
      target: cli
    container_name: symfony_cli
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - database
    networks:
      - symfony_network

  database:
    image: postgres:16
    container_name: symfony_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - symfony_network

  selenium:
    image: selenium/standalone-chromium:127.0
    container_name: symfony_selenium
    restart: unless-stopped
    ports:
      - "4445:4444"
      - "7901:7900"
    shm_size: 4gb
    networks:
      - symfony_network

networks:
  symfony_network:
    name: ${NETWORK_NAME:-symfony_network}

volumes:
  postgres_data: