services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - symfony_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=traefik"

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    networks:
      - symfony_network

  fpm:
    image: ghcr.io/davchs/github-workflow-example/fpm:0.1
    build:
      context: .docker/php
      target: fpm
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - database
    networks:
      - symfony_network

  cli:
    image: ghcr.io/davchs/github-workflow-example/cli:0.2
    build:
      context: .docker/php
      target: cli
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - database
    networks:
      - symfony_network

  database:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - symfony_network

  selenium:
    image: selenium/standalone-chromium:127.0
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 4gb
    networks:
      - symfony_network

networks:
  symfony_network:
    name: symfony_network

volumes:
  postgres_data:
