# Codeception Acceptance Test Suite Configuration
#
# Perform tests in a browser by either emulating one using PhpBrowser, or in a real browser using WebDriver.
# If you need both WebDriver and PhpBrowser tests, create a separate suite for each.

actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
              browser: chrome
              url: 'http://nginx'
              host: '127.0.0.1'
              port: 4444
              window_size: maximize
              restart: true
              capabilities:
                  chromeOptions:
                      args:
                          - '--headless'
                          - '--disable-gpu'
                          - '--no-sandbox'
                          - '--ignore-certificate-errors'
                  acceptInsecureCerts: true

              env:
                  - APP_ENV=test
        - Db:
            dsn: 'pgsql:host=127.0.0.1;dbname=symfony_test'
            user: 'user'
            password: 'password'


# Add Codeception\Step\Retry trait to AcceptanceTester to enable retries
step_decorators:
    - Codeception\Step\ConditionalAssertion
    - Codeception\Step\TryTo
    - Codeception\Step\Retry
