name: ViennaPHP Meetup

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  APP_ENV: test
  XDEBUG_MODE: 'off'

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: "${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}"
      - run: composer install

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: node_modules/
          key: "${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}"
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: public/build
          key: "${{ runner.os }}-build-${{ hashFiles('public/build') }}"
      - run: npm install
      - name: Run Webpack Encore build
        run: npm run build

  php-cs-fixer:
    needs:
      - composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: "${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}"
      - run: composer install
      - name: Run PHP-CS-Fixer
        run: composer run cs-check

  psalm:
    needs:
      - composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: "${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}"
      - run: composer install
      - name: Run Psalm
        run: composer run psalm

  unit-tests:
    needs:
      - php-cs-fixer
      - psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: "${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}"
      - run: composer install
      - name: Run Unit Tests
        run: ./vendor/bin/codecept run Unit

  functional-tests:
    needs:
      - php-cs-fixer
      - psalm
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:16
        env:
          POSTGRES_DB: symfony
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name database
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor/
          key: "${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}"
      - name: Setup environment
        run: |
          cp .github/workflows/environment/.env .env.local
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --env=test --no-interaction
      - name: Run Functional Tests
        run: ./vendor/bin/codecept run Functional
